version: "3.4"

services:
  cache:
    image: memcached:1.4-alpine

  db:
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
    image: postgres:9.6
    ports:
      - 5432:5432
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
  jobs:
    env_file: .env
    build: .
    volumes:
      - ./code:/usr/src/app
    command: bundle exec rake jobs:work
    depends_on:
      - db

  app:
    env_file: .env
    build: .
    labels:
      traefik.docker.network: dev
      traefik.frontend.rule: HostRegexp:hours.localhost,{subdomain:[a-z]+}.hours.localhost
      traefik.port: 8080
    volumes:
      - ./code:/usr/src/app
    depends_on:
      - db

networks:
  default:
    external:
      name: dev